---
- name: Include package type specific vars.
  include_vars: "apt_systems.yml"
  tags:
    - always

- name: Install packages via apt
  apt:
    name: "{{ paddles_extra_packages|list }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  tags:
    - packages

- name: Install docker packages
  apt:
    name: "{{ paddles_docker_packages|list }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  when: paddles_containerized
  tags:
    - packages
