---
paddles_extra_packages:
  # The following is a requirement of ansible's postgresql module
  - python3-psycopg2
  # The following packages are requirements for running paddles
  - git-all
  - python3-dev
  - python3-pip
  - python3-virtualenv
  - virtualenv
  - postgresql
  - postgresql-contrib
  - postgresql-server-dev-all
  - supervisor
  # We use nginx to reverse-proxy
  - nginx
  - liblz4-tool

paddles_docker_packages:
  - docker.io
  # docker swarm needs the requests module
  - python-requests
  - python-docker

# We need this so we can disable apache2 to get out of the way of nginx
apache_service: 'apache2'

supervisor_conf_d: /etc/supervisor/conf.d
supervisor_conf_suffix: conf
