---
# In non-Stream CentOS versions, ceph-cm-ansible takes care of overwriting the Distro/ISO-provided repo files.
# Since we convert from CentOS 8.X to CentOS Stream, we have to delete the Stream repo files that the process creates.
# We just don't want to rely on CentOS' infra to provide our mirror lists.  It has bitten us in the past.
- name: Clean up Stream distro-provided repos
  shell: "rm -rvf /etc/yum.repos.d/*-Stream-*"
  when:
    - ansible_lsb.description is defined
    - '"Stream" in ansible_lsb.description'

# Setting this var will add "-stream" to the mirrorlist/baseurl URLs in .repo files
- set_fact:
    dash_stream: "-stream"
  when:
    - ansible_lsb.description is defined
    - '"Stream" in ansible_lsb.description'

- name: Include CentOS Stream specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | regex_replace(' ', '_') }}_{{ ansible_distribution_major_version }}_stream.yml"
    - empty.yml
