---
# vars specific to centos 8 stream
# Should be in addition to or in replace of vars in centos_8.yml

additional_yum_repos:
  CentOS-PowerTools:
    name: "CentOS-$releasever - PowerTools"
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
